[package]
name = "interflux"
version = "0.1.0"
authors = ["Mark Rendle <mark@rendle.io>"]
edition = "2018"

[dependencies]
futures = "0.1"
config = "0.9.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
log = "0.4"
nom = "4.1"
bytes = "0.4"
hyper = "0.12"
clap = "2.32.0"